### ISSUE TITLE
Profile Schema: "control-id" is currently optional

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#1053]
"control-id" (https://pages.nist.gov/OSCAL/reference/latest/profile/xml-reference/#/profile/modify/alter/@control-id) is currently optional. 

As the containing statement is inherently non-operational without this value, it should either be changed to required, or explained in the profile specification.

I'd like to hear from @butler54 as well as the NIST team (pinging @david-waltermire-nist @wendellpiez so they see this) on their thoughts between these two options.

**Comment by wendellpiez** [comment]
The only rationale that occurs to me for `control-id` being optional is in view of possible extension of the semantics of `alter` to address other elements (besides controls). However that is a hypothetical, arguably unlikely (given the purpose of profiles), and up to us in any case.

To preserve some wiggle room however and to avoid backward-incompatible thrashing in the XSD/JSON Schema, the requirement could be expressed as a cardinality constraint rather than as a part of the definition. (I.e. min-occurs=0 but add a constraint to require it). Depending on whether and how easily constraints can be layered (in or out), that offers more flexibility. (I am fine with either.)

The profile resolution spec IMO should state that the flag is expected and there is an error condition (either reportable or just GIGO -- at least, optionally reportable as a warning?) in profile resolution, if an `alter` does not resolve to a *single* target (irrespective of nominal validity issues in upstream).

This is similar to if I have clashing IDs and no map to resolve the clash (which can happen even if everything is schema-valid), except I am pointing to nothing instead of more than one thing. Error.

So my vote is definitely to address in the profile spec, irrespective of changes to schemas or new constraints.

**Comment by JustKuzya** [comment]
Hi, Wendell.

I also have an control ID question: when profile is resolved and there are modifications to the control ID, should not the ID be changed if the modifications are not only additions?

I get that by looking at the profile one can see changes separately, control references separately. But once resolved, though the UUID would be different, the references to the father/mother catalogs are not mandatory any more. So one can end up with a few catalogs where AC-1 has the ID, but essentially not an AC-1 anymore. ☹ Maybe something generic like AC-1-MODIFIED or AC-1-ALTERED

Possibly, I’m missing something. The thought occurred to me a while ago, but as I dug into catalog schema I did not find any mandatory enforcement of name changing like that.

DC

**Comment by wendellpiez** [comment]
@JustKuzya,

That is correct, there is zero guarantee that a control with id `ac-1` in a resolved profile would have any similarity to (any) `ac-1` in an upstream catalog. `alter` can do just about anything while 'nominal control identity' implicitly remains with the ID value.

Indeed with the new mapping feature there is no guarantee that `ac-1` was even identified as `ac-1` and not something else.

Users of profiles should understand this! Additionally, it is an opportunity for a profile resolver to supplement resolution with warnings about modifications judged (by whatever set of rules) to be out of bounds. (For example, maybe you have a rule to say that no new ID given in a map can be the same as any old ID in the resolved source, to detect 'creativity' with this. Etc.) Like traceability, that is an option a resolver could offer over and above "bare" resolution.

HTH - interesting question - @stephenbanghart and @david-waltermire-nist may also have perspective.

**Comment by butler54** [comment]
So my thoughts - I think it should be required but I'm happy to leave this to v2. But my recommendation is the text in the documentation is updated to say that it is expected to error without it.
