### ISSUE TITLE
Profile resolver has XSLT key based on `resource/@id` -- not needed?

### ISSUE THREAD

**Issue by galtm** [usnistgov/OSCAL#1081]
The file `src\utils\util\resolver-pipeline\oscal-profile-resolve-select.xsl` has two definitions of the same XSLT key. I believe the first is dead code because the resource element does not support an attribute named id. Can someone confirm that and consider removing the unused definition?
```
<xsl:key name="cross-reference" match="resource" use="'#' || @id"/> <!-- not needed? -->
<xsl:key name="cross-reference" match="resource" use="'#' || @uuid"/>
```
If it isn't dead code or will become operational when a future enhancement is made elsewhere in the code base, then I'd appreciate knowing more. Thanks!

**Comment by wendellpiez** [comment]
Yup, I noticed the same thing. This was left in place defensively but you're right it should be expunged.

(Asking was correct in this case, but the fault here is mine in letting the code handle the no-longer-schema-valid option, at least not without leaving a comment to say why.)

@galtm are you able to start making interventions into the code as well as adding tests in your branch? Assuming the tests run otherwise (and we have confidence in their correctness now or eventually), this could be timely.

If so @david-waltermire-nist would probably let us tie this Issue to the appropriate PR, so it closes when the PR is accepted.

**Comment by galtm** [comment]
> @galtm are you able to start making interventions into the code as well as adding tests in your branch? Assuming the tests run otherwise (and we have confidence in their correctness now or eventually), this could be timely.

@wendellpiez Yes, I can take care of this issue and tie it into the PR that I'm planning for the near future. Thanks for confirming that this line of code is not needed.

**Comment by galtm** [comment]
#1101 fixes this issue.
