### ISSUE TITLE
Include FedRAMP Tailored Profile example

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#116]
We should also include an example Profile for the FedRAMP Tailored Baseline. Spreadsheet with controls can be found [here](https://tailored.fedramp.gov/static/APPENDIX%20A%20-%20FedRAMP%20Tailored%20Security%20Controls%20Baseline.xlsx).

CC @wendellpiez

**Comment by anweiss** [comment]
@brianrufgsa was this something that was on the radar? or is Tailored being excluded for the time being. Would love to be able to do a quick gap analysis between the FedRAMP Tailored and Moderate/High profiles.

**Comment by brianrufgsa** [comment]
@anweiss FedRAMP Tailored is a concept. The first "flavor" or FedRAMP Tailored was Low Impact Saas (LI-SaaS). This is not something I've discussed with leadership yet. I've been asked to focus on the Low, Moderate, and High baselines for now, but once I have the mechanisms in place for those, an LI-SaaS profile should be fairly simple to publish.

The biggest reason it's lower priority is because the templates are different. One big goal for FedRAMP profiles is to automatically produce our templates - and eventually go from OSCAL to a FedRAMP SSP in MS Word or PDF. I can create that capability once and have it work for FedRAMP Low, Moderate, and High templates. Since the LI-SaaS template is different, it requires a separate development effort.

**Comment by anweiss** [comment]
Makes sense. Thanks for the clarification @brianrufgsa.

**Comment by david-waltermire-nist** [comment]
This has been done for at least a year. [Here it is](https://github.com/usnistgov/oscal-content/blob/master/fedramp.gov/xml/FedRAMP_LI-SaaS-baseline_profile.xml), and also in JSON and YAML formats. Closing.
