### ISSUE TITLE
master branch /docs/README.md needs to be updated

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#155]
A new note should be added or have the existing one update. 
Following links are broken:
Overview: https://github.com/usnistgov/OSCAL/blob/master/docs/prose/OSCAL%20Overview.md
Tag Library: https://github.com/usnistgov/OSCAL/blob/master/working/doc/schema/oscal-tag-library.md

## Dependencies:

n/a

## Acceptance Criteria
Update information providing the latest or, at a minimum, update the links to point to valid, updated files.

**Comment by wendellpiez** [comment]
This file is due to be replaced by the file here:

https://github.com/wendellpiez/OSCAL/tree/docs-redesign/docs

when #326 is accepted.

The new readme has (only) directions on how to install and run the site production. (The site itself should have links to the schema docs, etc.)

When #326 is accepted, this Issue can be reviewed and closed.

**Comment by david-waltermire-nist** [comment]
Done.
