### ISSUE TITLE
mailing list links dead

### ISSUE THREAD

**Issue by shawndwells** [usnistgov/OSCAL#164]
OSCAL mailing list URLs have been down since RSA conference. Is there another way to signup?

https://email.nist.gov/mailman/listinfo/oscal-dev

https://email.nist.gov/mailman/listinfo/oscal-updates

**Comment by iMichaela** [comment]
Link is working now. Sorry for the inconvenience.
![untitled](https://user-images.githubusercontent.com/13984545/39884323-858ed986-5457-11e8-94e4-dc6c1c9164b6.jpeg)

**Comment by iMichaela** [comment]
![untitled](https://user-images.githubusercontent.com/13984545/39884414-c2acf758-5457-11e8-8b63-eb44ed9035cb.jpeg)

**Comment by david-waltermire-nist** [comment]
Actually, these links are not resolvable outside the NIST network. This has been a long-standing issue with the NIST mailman listserv implementation. What does work are the [in-email commands](http://www.list.org/mailman-member/node10.html) supported by mailman.

You can use [oscal-updates-join@nist.gov](mailto:oscal-updates-join@nist.gov) to subscribe. You can also use [oscal-updates-leave@nist.gov](mailto:oscal-updates-leave@nist.gov) to unsubscribe.

This has been fixed in PR #165.

**Comment by shawndwells** [comment]
Thanks. Sent the EMails that @david-waltermire-nist called out. Received auto reply that requests are forwarded to an admin for approval.

Is OSCAL and associated lists open to the public?

**Comment by david-waltermire-nist** [comment]
@shawndwells Yes, any list member can post without moderation. Membership is moderated to keep out spammers and trolls. It looks like you have been approved.
