### ISSUE TITLE
Auto-translation of NIST controls to Controls Markdown Language for human editing and maintenance

### ISSUE THREAD

**Issue by rafael5** [usnistgov/OSCAL#1921]
# User Story:

As an OSCAL {stakeholder}, I ... want to be able to read and edit the controls in human readable form on the Github respository using a Controls Markdown Language.  

This is Controls Markdown Language would be similar to (and preferably compatible with ) the OpenControls YAML representation, but represent the OSCAL model.  This would allow all controls to be easily readable and maintainable by humans with only simple text editor.

## Goals:

Maintain all the controls in the Github repository using human-readable Controls Markdown Language.   This markdown format must be interchangeable (by automated scripts) to the current OSCAL XML  and JSON, but in human-readable and editable form.

## Dependencies:

1. The Controls markdown language needs to be compatible with and fully represent all nuances of the published NIST controls with no loss of information content or context.  
2. The Controls Markdown Language needs to be compatible and feed into  HTML/PDF document production pipelines  (either asciidoc  or  reStructuredText, leveraging either Pandoc or Sphinx document production libraries respectively).

## Acceptance Criteria

The Controls Markdown Language needs to pass 
1.  Automated  validation against existing  OSCAL XML/JSON formats to preserve all content
2. Automated validation testing against the  original NIST published control 
3. Automated document production (HTML/PDF) using  either reST/Sphinx or  asciidoc/Pandoc.

**Comment by wendellpiez** [comment]
... main reason being (I concur) even if this is only a tracker for now, it is best not buried altogether, mainly b/c good ideas will often come back around.

FTR, I think this idea is awesome, it just needs more specification, design/development, perhaps proof-of-concept. However, the idea of what amounts to a custom bespoke grammar for OSCAL is pretty open ended and could go in many directions - to say nothing of how it should be validated, interfaced it with (canonical, metaschema-based XML- or object-notation) OSCAL. etc.

**Comment by iMichaela** [comment]
@wendellpiez and @aj-stein-nist - Isn't this issue addressed, in principle (because I did not test it), by the [IBM Compliance Trestle -> Authoring module?](https://ibm.github.io/compliance-trestle/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring/)

~
The purpose of the **authoring tools** is to allow selected edits of OSCAL documents guided by prompts for where content is required. This serves to streamline the edit/approval process whereby the author **is presented with one markdown document per control**, and it provides a view of the the key information needed during the editing process. This greatly simplifies the editing process compared to multiple authors working together on a single large JSON document.

**The key modes of authoring are -generate and -assemble. During -generate a JSON document is converted to markdown format, allowing authors to add or edit prose and parameter values. After editing, the markdown can then be -assembled into the same or a new JSON document that captures the edit changes.**
~

**Comment by aj-stein-nist** [comment]
I agree that it is a possible idea, but since originally reported in 2019, no recommendation for a draft specification or tool agnostic way has come up. Given that compliance-trestle has implemented their own way of doing this and not requested it be adopted by other tools, I am going to close this for now. If anyone has ideas of how to move forward with it, they can always comment or request to reopen it.

**Comment by wendellpiez** [comment]
:+1: Indeed, Compliance Trestle may well have taken this approach: it's the kind of good idea that keeps coming back.
