### ISSUE TITLE
Avoid http name spaces

### ISSUE THREAD

**Issue by OR13** [usnistgov/OSCAL#1933]
https://github.com/usnistgov/OSCAL-Pages/blob/develop/src/content/learn/tutorials/general/extension.md

http://csrc.nist.gov/ns/oscal -> https://csrc.nist.gov/ns/oscal

**Comment by aj-stein-nist** [comment]
Hi @OR13 👋, long time no see. Just a heads up, I moved this to the correct model and spec repo instead of the content site repo as the request about namespace URIs is lower level than just the extension docs. Can you explain your rationale for this request?

I know this used to trip me up earlier in my involvement OSCAL schemas and other security data formats, but the namespaces are really identifiers (namespaces after all) even if they happen to resemble URLs, they are not intended to be accessed and thus historically speaking (at least in the XML tradition), inside and outside of NIST, they are often http. Changing the core OSCAL namespace would be a backwards breaking change at this juncture, so  I would like to know more about why you would want this change.

**Comment by OR13** [comment]
When you use http namespaces you often end up with consuming software doing exact string matching, or exposing http links directly to developers or analysts.

schema.org used to have http namespaced terms.

Then at some point you want to upgrade to https, and all that logic that looks for http:// breaks.

If you are processing RDF or other formats, you need to add a bunch of OWL same as or other stuff.

I recommend the following:

1. If you must use URLs start with them as https.
2. Consider not using URLs, especially if they don't result in resolvable terms or good user experience anyway

**Comment by OR13** [comment]
I understand if it's too late to apply this feedback, but if there is a chance it will get done later, the earlier it happens the mess it hurts.

**Comment by OR13** [comment]
Example: https://github.com/schemaorg/schemaorg/issues/2853

**Comment by aj-stein-nist** [comment]
Hi again, @OR13, I discussed with the team and we confirmed that changing the default namespace, be it for the specification or the reference implementations, and most importantly [pre-existing commmunity software](https://pages.nist.gov/OSCAL/resources/tools/) conforming to the spec, this proposed recommendation will be a breaking change across the 1.x releases. At this time, we are unable to consider this request. When considering the long-term trajectory of OSCAL (distant future versions, 2.x, 3.x, and beyond) where there is not a strict requirements on our commitment to [backwards compatibility](https://github.com/usnistgov/OSCAL/blob/main/versioning-and-branching.md#versioning), feel free to reopen this issue. Project leadership will review these issues for consideration during long-term planning of long-term future changes.

With that, I will mark this as not planned and closed. Thanks for your issue and taking the time to explain your position.
