### ISSUE TITLE
Define an allowable subset of markdown syntax for prose

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#200]
# User Story:

As an OSCAL maintainer, I have defined an allowable subset of markdown syntax which can be used to express prose. The markdown is subsequently properly encoded in XML and JSON.

## Goals:

A subset of markdown capabilities has been selected from the [official markdown](https://daringfireball.net/projects/markdown/syntax) and flavored/alternative markdown syntaxes (e.g. [CommonMark](http://commonmark.org/)) for use in prose. This also needs to be done in a manner that prohibits the embedding of malicious content in prose.

## Dependencies:

None. Not a blocker, but something to note -> http://roopc.net/posts/2014/markdown-cfg/. TL;DR markdown is too ambiguous to allow for the creation of a formal context-free grammar. This could potentially make extraction of inserted parameters, etc more challenging.

## Acceptance Criteria

A subset of markdown syntax, in addition to plain text, is allowed in prose fields. These fields are properly encoded in both XML and JSON.

**Comment by wendellpiez** [comment]
While I believe that markdown in general defies a CFG, this is largely due to features such as HTML-embedded-in-markdown, or the need otherwise to support arbitrary markup delimiters (angle brackets!) floating around. I would like to see OSCAL's markdown+plus+insertion notation be so small and tight that parsing it becomes (relatively) a non-issue. Indeed all by itself I think this is a reason to keep it small and tight.

As for malicious content, I hope we can achieve sufficient defense by ensuring mappings are *only* to known (XML/OSCAL/HTML) element semantics e,g, `<em>` and whatever, or to the (very narrowly constrained) parameter callout/insertion semantics.

**Comment by wendellpiez** [comment]
This Issue should reference https://github.com/usnistgov/OSCAL/blob/master/docs/schema/html-markdown-format-mapping.md

To note, I also have a (short!) features list for this syntax. I would like to support HTML `<q>`, a valid (if not widely used) inline element useful especially in better-controlled environments (such as ours), where it can be watched. Markdown can be `"quote"` `<q>quote</q>`. We also need support for bulleted and numbered lists and probably `<pre>`.

**Comment by anweiss** [comment]
@wendellpiez could you maybe put together a grammar for the features you envision so we can use that as a starting point for building upon this issue?

**Comment by JJediny** [comment]
Based on discussions to date 06/15/2018, the OSCAL JSON schema will support limited Markdown in the `prose` attribute loosely based on Github flavored Markdown:

# To Be Supported (Proposed)

- [ ] Headings
```
# Heading 1
## Heading 2
### Heading 3
#### Heading 4
```

- [ ] Emphasis
```
**bold**
*italics*
~~strikethrough~~
```

- [ ] Lists
```
* Generic list item
* Generic list item
* Generic list item

- Generic list item
- Generic list item
- Generic list item

1. Numbered list item
2. Numbered list item
3. Numbered list item
```

- [ ] Links
```
[Text to display](http://www.example.com)
```

- [ ] Quotes
```
> It can span multiple lines!
```

- [ ] Images
```
![](http://www.example.com/image.jpg)
```

- [ ] Code/Raw Text
```
`Line`
```

```
```Block```
```

# Not Supported (Proposed)

- [ ] Tables
```
| Column 1 | Column 2 | Column 3 |
| -------- | -------- | -------- |
| John | Doe | Male |
| Mary | Smith | Female |
```

# References:
https://guides.github.com/features/mastering-markdown/

**Comment by wendellpiez** [comment]
I would like to start with the barest minimal subset of markdown, leaving out headers and any internal structure such as block quotes other than fenced code blocks, inline elements (bare minimum!) and lists.

This is both for (manifold) practical reasons plus also philosophical reasons: that stuff implies structures that should be expressed in OSCAL (for example by means of nested parts) rather than having to be interpolated.

Note for SP800-53 the bare minimum is supporting parameter injection. Other catalogs have some scattered things but it's mainly at higher levels that prose will have to be more flexible.
Also, if we start small we can be tightly requirements-driven.

**Comment by wendellpiez** [comment]
@anweiss I have been messing towards a grammar, but I have also (I admit it) been pondering an evil notion of doing the old Perl-style hack-the-tags approach in XSLT. (Basically: sequentially map markdown signals via regex to markup; then try to parse the markup.) If the syntax is small enough this could be effective enough help to stovepipe this issue. (As we already have HTML->md conversion.)

A proper and correct grammar would be awesome however. Please advise with any ideas.

**Comment by anweiss** [comment]
@wendellpiez indeed, let's keep the syntax small. The primary reason I proposed a grammar is to give tool developers a foundation on which to implement our proposed markdown subset. It formalizes it a bit.

**Comment by wendellpiez** [comment]
@anweiss Agreed 100%. Would love to see a grammar (help wanted?) and even for only part of it, such as the inline level (i.e. w/in `p` or `li` content), leaving the block level parsing to be hacked.

**Comment by anweiss** [comment]
Happy to help. Can you list out exactly what you have in mind so we can come to a consensus on @JJediny's proposed items?

**Comment by wendellpiez** [comment]
@david-waltermire-nist has already produced his take on this. Personally I am agnostic to the b-vs-strong, i-vs-em question, though I guess I'd lean towards the explicitly presentational (rather than putatively-though-not-necessarily-actual "semantic"), so:

* parameter insertion point
* `b` (or `strong`)
* `i` (or `em`)
* my favorite underutilized HTML tag, `q` (very useful)
* `code`
* simple inline anchors nothing fancy
* Perhaps `u`, to satisfy the pedants (er, "creatives") who wish fuller access to a range of inline effects
* `sup` and `sub` in some form, b/c they are unfortunately unavoidable

I also think it's probably wise, whatever the subset is, that we also consider the superset (not to be implemented yet), if only to familiarize ourselves with what people might be asking for. :-)

Containment among these elements (expressed inline) is not absolute: for example, the ideal grammar might permit `b/i` but not `b/b` etc etc.... it seems reasonable to forbid `sub` anywhere inside `sub`, and so forth. It'll be interesting to see what you come up with.

(This could be a Balisage paper ... a follow-on to https://www.balisage.net/Proceedings/vol19/html/Flynn01/BalisageVol19-Flynn01.html ?)

**Comment by wendellpiez** [comment]
Additional note: to be complete, a markdown syntax must support escaping magic characters, agreed? Also, failure behavior (what happens if markdown fails to conform to the grammar) must be specified. Finally (today?), food for further thought - rather than binding to (reflecting a model for) HTML, maybe a full-fledged OSCAL markdown should bind to OSCAL, or to a subset of OSCAL (such as limiting the nesting of parts)? So, no block quotes, but (classified or named) properties and parts.

What would be the tradeoffs of such a notation vs the XML or JSON or (say) YAML (which has also been mentioned)? Is OSCAL clean and simple enough for it to be feasible?

**Comment by JJediny** [comment]
To support:
```
| Format Type   | JSON/YAML (Markdown)                                | XML (HTML)                                                                     |   |   |
|---------------|-----------------------------------------------------|--------------------------------------------------------------------------------|---|---|
| Bold          | **text**                                            | <b>text</b>                                                                    |   |   |
| Italics       | *text*                                              | <i>text</i>                                                                    |   |   |
| Qoute         | >text>>text                                         | <q>text</q>                                                                    |   |   |
| Code - Inline | `text`                                              | <code>text</code>                                                              |   |   |
| Code - Block  | ```text```                                          | <code>text</code>                                                              |   |   |
| Bullet List   | * text* textor- text- text                          | <ul>  <li>text</li>  <li>text</li></ul>                                        |   |   |
| Numbered List | 1. text2. text3. text                               | <ol>  <li>text</li>  <li>text</li>  <li>text</li></ol>                         |   |   |
| Strikethrough | ~~text~~                                            | <s>text</s>                                                                    |   |   |
| Superscript   | ^text^                                              | <sup>text</sup>                                                                |   |   |
| Subscript     | ~text~                                              | <sub>text</sub>                                                                |   |   |
| Headings      | # text## text### text#### text##### text###### text | <h1>text</h1><h2>text</h2><h3>text</h3><h4>text</h4><h5>text</h5><h6>text</h6> |   |   |
| Checkbox      | - [ ] text                                          | <input type="checkbox>text<br>                                                 |   |   |
```
Not supported:
- tables
- references/footnotes
- horizontal rule

@wendellpiez while agree headings should be discouraged, the functionality should still be supported.

**Comment by anweiss** [comment]
@JJediny can you maybe put the markdown syntax in its own column, and split the `JSON/YAML` column into two, with one showing the encoded markdown in a JSON string, and the other showing encoded markdown in a YAML string? This will just highlight any dependencies on special characters that may need to be properly escaped/quoted in JSON and YAML.

**Comment by david-waltermire-nist** [comment]
This is addressed in more specific issues. closing.
