### ISSUE TITLE
Finishing and testing the edges of metaschema support for JSON

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#202]
# User Story:

As an OSCAL developer relying on the JSON schemas, I need to have confidence that the constraints they enforce guarantee the fitness of my data for conversion to OSCAL XML (among other uses). Among other things this requires a functional alignment between the constraints over objects and properties expressed in the JSON Schema, and elements and attributes expressed in XSD, so that any 'garbage in' can be detected before handing to a conversion script, if not prevented altogether.

## Goals:

Ensure that OSCAL JSON Schemas (as produced from metaschema) are fully aligned with the XSDs with respect to supported features. Features that are not supported in JSON Schema need to be described, isolated and ideally supported by other means.

Known issues/opportunities include:
  * Validating uniqueness of ID values on `id` flags (catalog scope)
  * Other data types such as `anyURI`, `IDREF`, `NCName`
  * Implementing metaschema `<choice>` as JSON Schema `oneOf`

## Dependencies:

* A stable metaschema infrastructure to test and build on (#186)
* Unit tests for features and edge/error conditions such as clashing IDs (cf #153).

## Acceptance Criteria

We have documented metaschema and its features, including the semantics of metaschema's expressions via both XSD and JSON. (Do we need a metaschema for the metaschema?) By means of our unit tests, we have confidence that the XSD and JSON pathways are aligned and consistent, with their points of difference well understood.

**Comment by anweiss** [comment]
The work for this issue is already underway. I'll push to a feature branch soon. Essentially, for each metaschema `assembly`, `field`, and `flag` definition, there exists a corresponding unit test. Each test will validate the structure of the JSON schema, including the expected equivalent data types/regex constraints, choices, etc. We can also incorporate checks against ID uniqueness, keeping in mind that if IDs are to be used as JSON keys, that our checks will go above and beyond the core JSON spec ... aka, the JSON spec itself does not enforce unique keys, but rather the ecosystem has generally accepted that keys must be unique.

**Comment by wendellpiez** [comment]
Awesome @anweiss 

wrt key constraints, uniqueness constraints - actually the current metaschema in principle ought to support an in-between model namely enforcing uniqueness of a value only among siblings - which could be useful in cases where there are singleton constraints on flags. :-) But this blurs into the 'OSCAL declarations' model ... currently it supports IDs b/c (as you say) the ecosystem warrants this usage, so it is transparent and well-understood. (Also because the objects in question namely controls and parameters need system-wide IDs for other reasons.)

I am groping my way forward with the unit tests as well but there is much to do.

**Comment by david-waltermire-nist** [comment]
This is addressed by a number of existing issues. Closing.
