### ISSUE TITLE
Missing optional "required" attributes in some metaschema elements

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#243]
The metaschema's own schema (https://github.com/usnistgov/OSCAL/blob/master/build/metaschema/lib/metaschema.xsd) is missing an optional `required` attribute for the following element definitions:

- [`m:assembly`](https://github.com/usnistgov/OSCAL/blob/master/build/metaschema/lib/metaschema.xsd#L145)
- [`m:assemblies`](https://github.com/usnistgov/OSCAL/blob/master/build/metaschema/lib/metaschema.xsd#L154)
- [`m:fields`](https://github.com/usnistgov/OSCAL/blob/master/build/metaschema/lib/metaschema.xsd#L175)

Without this attribute, one cannot mark an `assembly`, `assemblies`, nor `fields` element as required in a `define-assembly` assembly definition `model`.

Related to #202 

CC @wendellpiez

**Comment by wendellpiez** [comment]
@anweiss this is so awesome this is the level of shakeout we need.

Actually I left `required` off these three elements on purpose. On the principle of "closest fit" (analogous to least privilege) - that I don't actually want to permit anything but single fields (`m:field`) to be "requirable" or (by the schema) required.

If you can offer a use case for where you might wish multiple fields or assemblies to be required (which presumably would mean "at least one"), we can certainly consider this. In the case of single assembly `m:assembly`, I hadn't seen one at design time and decided not to go look hard.

A further thing to keep in mind is that at least as far as OSCAL catalogs (and in principle profiles) are concerned, we also have the OSCAL declarations layer, where you can say "require and permit only a single assembly with class='statement" ... irrespective of the fact that the class is assigned to `part` assemblies (which on their layer -- the OSCAL schema -- have  zero-or-more cardinality for maximum freedom).

This doesn't mean there is no use case for the feature in general which is why I'm open.

**Comment by anweiss** [comment]
This info is quite helpful, thanks. So thus far, I've interpreted the `required` attribute to mean that the field is optional, which in turn, translates to the respective empty/"0" value for that type in JSON. Otherwise, one has no way of knowing from the assembly's model whether or not the field should be output as its empty value or omitted altogether if no data exists.

**Comment by wendellpiez** [comment]
Lemme add to this that the XML Way is to Omit The Value When It Does Not Exist. 👌 Emitting an empty value we do only as a stopgap. This is not to say that empty values aren't permitted; there is usually no way to prevent them. (Although they can be found easily enough.) Similarly they are generally ignored (treated as though not even there) when given. Providing empty values only to (for example) meet validation requirements -- the classic `<title/>` ... would be ... an indication of some kind of fudging going on.

Of course this isn't true in other sorts of environments. But if the JSON were to follow the XML principle, it would be "assume everything is optional and don't represent it unless there's actually a data value".

**Comment by wendellpiez** [comment]
#344 will entail making it possible for a metaschema to declare an `assembly` as required.

An open question is whether we should extend the functionality to `fields` and `assemblies` on the principle that metaschema authors should be able to do what they want, at least if it translates easily (and this does). This would go against the principle that metaschema authors should be able to do only what we know they need to be able to do.

**Comment by david-waltermire-nist** [comment]
@wendellpiez We should do all of what you are suggesting. For example, fields can be 0-many as optional, or 1-many as required.

**Comment by iMichaela** [comment]
## 5/23/2019
@wendellpiez is working on it. Estimates to be done in a few days.

**Comment by wendellpiez** [comment]
Now committed, with PR here: #379.

**Comment by david-waltermire-nist** [comment]
Done.
