### ISSUE TITLE
Develop a tool to perform FedRAMP validations based off a candidate list

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#272]
# User Story:

As an OSCAL content consumer, I can run a tool to validate an SSP in OSCAL format based off a draft list of FedRAMP validations.

## Goals:

Develop a tool to perform validations based of a draft list of FedRAMP validations that can be quickly implemented (#271)

## Dependencies:

#271  and #270 

## Acceptance Criteria

1) A tool exists and can be run to validate an SSP in OSCAL format based off a draft list of FedRAMP validations.

**Comment by brianrufgsa** [comment]
12/20/2018 @brianrufgsa provided list of all SSP Validation activities. Will work with @wendellpiez to automate 3-5 of these as a proof of concept.
Work in Sprint 17.

**Comment by wendellpiez** [comment]
** Progress Feb 7 2019 **

I have underway an XSLT 1.0 transformation (stylesheet) that produces a readable view of SSP data (control summary info), using a web browser. It already indexes control summary statements by their (nominal) implementation status, and provides a basis for more / similar breakouts, analysis and validations. The data is as extracted from a sample Word document using an experimental conversion pipeline.

I can demo this (won't take long) but it needs more work. Suggest a work session with @brianrufgsa @iMichaela and/or others to determine next steps including more possible validations to perform over this data or data like it. (But the demo is not in Github since the data is proprietary.) An hour could suffice for this, to scope out what I should do next.

% complete: 40% ? depends on how close this data is to the data format we eventually define for SSP data.

**Comment by brianrufgsa** [comment]
This depends on the test-case data being in a minimum viable state. We continue to make progress on that as well.

**Comment by wendellpiez** [comment]
I am sending to @brianrufgsa an XSLT 1.0 stylesheet that can be applied to a sample SSP-OSCAL data set, producing a Control Implementation Summary, in almost any browser. It delivers the tests described on #271.

**Comment by brianrufgsa** [comment]
This is on hold while I focus on a tool for creating and managing OSCAL catalogs and profiles.

**Comment by redhatrises** [comment]
Having this integrated into OSCALKit would also be nice.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa Should this be transferred to the FedRAMP repo? If not, we should discuss how to close this out.

**Comment by wendellpiez** [comment]
Also noting that the current XML-based FedRAMP values list (which specifies supported values for FedRAMP constructs) would map straightforwardly into Schematron via a single-pass transformation: for an XSLT developer familiar with Schematron, this should not be difficult (i.e. requiring hours not days). Separate Issue for that?

See files in https://github.com/GSA/fedramp-automation/tree/master/resources/xml especially `fedramp_values.xml`.

**Comment by brianrufgsa** [comment]
Created gsa/fedramp-automation#56, which is more on-target for what is needed at this time.
Closing this issue.
