### ISSUE TITLE
OSCAL Website - Catalog Data Autogeneration

### ISSUE THREAD

**Issue by howieavp76** [usnistgov/OSCAL#318]
# User Story:

As an OSCAL collaborator, I want easy access to content related to the OSCAL schema documentation so that I can learn more about the standard and get involved.

## Goals:

- Auto-generate catalogue data from the XML schema
- Apply initial formatting to the HTML to improve readability and user experience
- Develop a repeatable publishing workflow including Git commands 

## Dependencies:

Dependent upon Issue # 294

## Acceptance Criteria

- Rough catalogue data available from auto-generation
- Bugs in HTML resolved; resulting in a nicely formatted set of self-maintaining documentation
- Git workflow published in the project Wiki

**Comment by howieavp76** [comment]
@iMichaela - this story is ready to add to the sprint backlog pending your approval

**Comment by howieavp76** [comment]
- Pulled down merged content from Andrew and Wendell.  
- Initial content being auto-generated via HTML.  
- Added Bootstrap CSS for formatting the auto-generated content
- Applied initial formatting to the oscal-catalog_address.html file as an example

**Comment by howieavp76** [comment]
@wendellpiez 

The following changes are made to the template to improve formatting:

- Removed span class that was generating the wonky labels
- Added Bootstrap classes to the unordered list content
- Added Bootstrap classes to the table
- Placed each item inside a Bootstrap panel with a color coded header so you can easily see when you have moved to a new element; all content is logically grouped together now
- Added color coding to help visually distinguish sections
- Changed the property "caption" to a "h4" header

Some questions/comments for you:

- Can you remove the  <code> markup? Not sure what this is doing and it will bring file size down
- There are some translation errors on the XML markup that need to be fixed
- Can you remove the "A" in front of the content list items

**Comment by iMichaela** [comment]
@howieavp76 : Per last meeting notes, I created the issue #311 that covers exclusively the website review, and lists all other related issues. Appears to me that the current issue (#318) is covering the website development/implementation. 

The following issues are also related to the OSCAL website development. 
#297: Pages Hero Graphic,
#298: Pages Learn More,
#299 Pages Contact
#300 Pages Get Involved
#301 Pages Producers Overview
#302 Pages Consumer Overview

Also, the following issues could be considered to be addressed for now, if there are pages created for “Scenario” and “Case Study”. The content will need to be developed and maintained later on:
#303 Pages Scenario
#304 Pages Case Study
#305 (Epic) Datasheets to support OSCAL Website.

_I suggest we  keep the #311 for the website review, when the site is ready, and all discussed content is in place. **I suggest updating the title of this issue to summarize the work performed (auto-generation and formatting of the documentation for the catalog and profile pages)**, so we can close it when you are done. I have comments regarding the content of some pages but did not finish reviewing all pages since the site is still a moving target. We also need Jim Foti to review the site, but we will do the content review under #311, when you will be done with all pages._

**Comment by howieavp76** [comment]
I renamed to focus on auto-generation per your request.  When you have content updates, feel free to send my way.

[https://d4d8xd20er8lg.cloudfront.net/3277cffd-eee8-40cd-8516-ba9596da9139/WKqQRUyXt7qJtVR6hdqPKd7gFnUSNcGr.jpeg]

Travis Howerton
Co Founder and CTO, C2 Labs

A 777 6th Street NW 11th Floor, Washington, DC 20001
P 202-975-0857 <tel:202-975-0857>


E thowerton@c2labs.com <mailto:thowerton@c2labs.com>


W http://www.c2labs.com/<http://www.c2labs.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>



[https://s3.amazonaws.com/images.wisestamp.com/social_icons/square/linkedin.png]<https://www.linkedin.com/in/travishowerton/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by wendellpiez** [comment]
@howieavp76 please check to make sure I have addressed your line items. I had to guess on a couple of them.

**Comment by howieavp76** [comment]
@wendellpiez - have the XML workflow going end to end.  Updated the formatting and will republish back to Andrew's branch.  New look and feel shown below (minimal CSS that is USWDS compliant, removed all Bootstrap):
![screen shot 2019-03-04 at 11 43 30 am](https://user-images.githubusercontent.com/33614714/53748333-284ff280-3e73-11e9-98fe-fe5b106aff52.png)

**Comment by brianrufgsa** [comment]
3/7/2019 - Addressed by Issues #286 and #311. We are closing this to eliminate redundancy.
