### ISSUE TITLE
ID and reference-to-ID not defined clearly

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#348]
# User Story:

As an OSCAL developer and user, I need all the names and naming conventions to be consistent, for predictability. There are still one or two small issues. One of them is the name of attributes (flags) called 'id'.

On most elements, its `@id` is its identifier. (So, `<control id="ac-1">`.)

When an element needs to point to another, the name of the pointer indicates the type of the target, So we have (for example):

```
<call control-id="ac-2"/>
<call subcontrol-id="ac-2.1"/>
```

However this rule is not followed in the case of parameter settings, which now have `<set-param id="cm-6_prm_1">`. For consistency (and so we can add an @id to the set-param if/when we need to) this should be `<set-param param-id="cm-6_prm_1">`

The profile and catalog schemas should also be reviewed for similar issues.

## Goals:

Make the schemas smoother, more consistent and more predictable wrt the intended tagging usage.

## Dependencies:

None (known)

## Acceptance Criteria

* Metaschemas are amended
* Schemas and artifacts are updated
* Data sets are modified to the new attribute names and valid to the new schemas
* Schema documentation has appropriate language guiding users on the use of `@id` and `@x-id` where x-id includes `@control-id`, `@param-id` etc.

**Comment by anweiss** [comment]
I think this is a good proposed change. Keeps things consistent in terms of `id`'s of the elements themselves vs. the referenced `id`'s that an element is `set`'ing, `call`'ing, etc

**Comment by brianrufgsa** [comment]
Wendell and I discussed this at some point, and I am also in favor of this change.

Whenever something is being assigned an id, the attribute should always be @id. 
When one element is referencing another element by @id, it should always do so using @[element-name]-id

BRAINSTORMING SUGGESTION:
It would be great if there was a way to define this in the metaschema. Any define-field or define-assembly structure that specifies an @id flag must also include a "reference-as" element or attribute, which indicates the correct way other elements should reference this element when using its defined @id value.

Metaschema processing could then:
1. Ensure each "reference-as" name is unique within the layer.
2. Build downstream checking into the XSD files that ensures only valid references are used.

NOTE 1: I do not know how difficult or practical it is to implement these in the metaschema processing, and recognize we likely have higher priorities for now - even if we agreed on this conceptually.

NOTE 2: My suggestion above works well with named elements, and I feel strongly about it for those; however, this does not work as well with part or prop elements, since they are used to expand the syntax. It may be appropriate to have different (more descriptive) id references for part depending on how it is used. The same for prop.

**Comment by iMichaela** [comment]
## 5/23/2019
@wendellpiez is working on it. Estimates to be done in a few days.

**Comment by wendellpiez** [comment]
Question for @david-waltermire-nist @anweiss @brianrufgsa and contributors - what do you think of changing `set-parameter` to `set`? So far, the only things we have to set are parameters. It would look like

```
<set param-id="paramX">
  <label> ... </label>
  <constraint> ... </constraint>
  <value> ... </value>
</set>
```

Note: this is only in profiles. In catalogs, we have `<param id="paramX">`.

The alternatives are to leave this as `<set-param param-id="paramX"/>` or to come up with another name entirely.

**Comment by brianrufgsa** [comment]
I agree with this suggestion and support it.

**Comment by wendellpiez** [comment]
Another question - a tangent - is which objects in the JSON should be addressed using a flag value such as an ID -- meaning they can appear in the JSON as labeled objects, not as (unlabelled) members of a (labeled) array, and flattening one level. So far, we have parameters and subcontrols behaving this way. Arguably, either controls should also use this feature, or subcontrols should not. Parameters should probably use the feature b/c they frequently occur singly so the flattening optimization is more significant.

@david-waltermire-nist @anweiss @brianrufgsa @howieavp76 please feel free to offer thoughts (on another Issue if appropriate). While the issue is not urgent it will be harder to make these changes later.

**Comment by anweiss** [comment]
+1 to @brianrufgsa. I'm for it.

re. JSON flattening, let's discuss this in #239.

**Comment by iMichaela** [comment]
I am for changing ‘set param’ with ‘set’ and I am strongly for ID consistency usage, but I would like to further discuss the JSON  ‘flattening’.

**Comment by wendellpiez** [comment]
The names of the element and attributes have been changed. The PR is #375.
