### ISSUE TITLE
profile-resolution-preview.html

### ISSUE THREAD

**Issue by garik-pilot** [usnistgov/OSCAL#674]
Great information but it is still not clear how to use the xml->xml transformation of catalog to get a target profile. It would be great if some examples would be provided on how to select the specific security controls (and enhancements, e.g. from nist800-53) to import and modify them and then to save in the target profile in xml format.  It would be interesting to look at examples of various scenarios (catalog->profile), (catalog->profile1->profile2), (catalog1 & catalog2->profile),...

**Comment by iMichaela** [comment]
@garik-pilot: Profile resolution is not focusing on creating the profile itself. Tutorials for generating profiles from a catalog were designed and will be released soon (most likely with the next website update). 
A profile in OSCAL represents a selection and configuration of a set of controls. In the normal case, the set of controls available to a profile is provided by a catalog. For example, the three NIST SP 800-53 profiles representing the impact baselines HIGH, MODERATE and LOW: each of these calls on a catalog representing the families, controls and control enhancements described in SP 800-53/53A. In a data processing system, this dependency can be modeled in the form of separate documents or data instances - the (nominal) catalog and its profile, the latter being a selection, adaptation and organization of controls, as distinct from the catalog from which those controls are derived.

However, profiles may also select controls from profiles, thus deriving them from underlying catalogs as modified by those profiles. This feature enables an organization that wishes to promulgate guidelines or requirements to do so by publishing a set of customizations to an existing catalog, rather than create a catalog from scratch. Profiles can also arrange combinations of controls from more than one catalog or profile origin, making it possible to use them to support the creation of hybrid catalogs.
When an author desires to make the profile 'look like a catalog" and have the data 'imported' into one file, then we 'resolve the profile'. The primary use case resolving a profile would be when we need to make a new, customized catalog to apply to a system or set of systems, starting from a canonical, received, mandated, or standard catalog with a more general scope.
Please see https://pages.nist.gov/OSCAL/documentation/specification/processing/profile-resolution/ for profile resolution details.

**Comment by garik-pilot** [comment]
I reviewed the profile resolution details, it is great information. Waiting
for the next web site update to look at the examples of how to generate the
profiles from the catalog to use in my daily work as the security architect
in FI.

**Comment by david-waltermire-nist** [comment]
@garik-pilot We are still working on the profile tutorials. In the mean time you can look at some profile examples:

- https://github.com/usnistgov/OSCAL/tree/master/content/nist.gov/SP800-53/rev4
- https://github.com/usnistgov/OSCAL/tree/master/content/fedramp.gov

The files that end with `_profile.xml`, `_profile.json`, and `_profile.yaml` are all OSCAL profiles.

The resolved versions of these files end with `-resolved-profile_catalog.xml`, `-resolved-profile_catalog.json`, and `-resolved-profile_catalog.yaml`.

**Comment by garik-pilot** [comment]
yes, I saw the example of profiles in various formats. I am looking for
examples of XSL files to execute the transformation
catalog.xml->my-exec.xsl->profile.xml.
as the beginner of OSCAL, I use the simplest way to use Saxon from the
command line (I will buy oXygen for sure):

java net.sf.saxon.Transform -t -s:catalog.xml -xsl:my-exec.xsl
-o:profile.xml

It would be great to publish a kind of "Getting Started" page for the folks
like me who just started to use OSCAL  I tried to configure GUI and cli
following the instructions on web site but I had the challenge (thanks
Brian to help me).

**Comment by david-waltermire-nist** [comment]
It looks like this question has been answered.

**Comment by wendellpiez** [comment]
@garik-pilot you should feel free to update us as to your current needs.

The idea of producing a profile programmatically from a catalog -- as opposed to the reverse -- is an interesting one. But it is not altogether clear that is what you want. In general, any transformation can be described as a function from inputs to results. An OSCAL profile includes in it, with its import statements, all information needed to produce a "catalog" representation of the profile in application; we call this transformation "resolution". The reverse operation is interesting to contemplate, however to process a catalog to produce a profile implies that the catalog be compared to a nominal baseline for that profile -- a secondary input. I can imagine workflows that could use such a transformation -- but the end result being a profile, and a profile being a data object that most OSCAL users will not be producing (or will they?) but rather consuming -- it is not clear to me that specifying and implementing it at this point is a priority.

It would be one way to produce profiles, however. If this is actually the use case it might be interesting to explore.

**Comment by wendellpiez** [comment]
@garik-pilot @david-waltermire-nist I am rereading the OP, and there is an interesting use case additional to the one I just described above ... a simpler XSLT that would simply produce a valid profile when given (a) a nominal catalog to address, and (b) a list of control selections to be expressed in reference to that catalog.

I can see the potential usefulness of such an XSLT, but it hides a design problem, namely the interface, i.e. how would the list of selected controls (and perhaps their modifications) be presented to the transformation? Here, the main problem is scoping the use case, since the simpler the set of requirements the simpler the interface will be. Is selection by exclusion supported, for example? Can I use XML syntax?

But even a very simple demo could be an effective illustration. @garik-pilot if we are finally getting your drift here, when you update us you can tell us whether/when we should invest in making such a tool.
