### ISSUE TITLE
results_group naming syntax

### ISSUE THREAD

**Issue by adamb-kpmg** [usnistgov/OSCAL#717]
{Please enter your question.}
Is it intentional that assessment-results/results_group:
1) has an underscore in the name instead of the dash
2) is called results_group instead of results?

If not, I propose that this be named results to be consistent with the other names in this structure (e.g., "findings" is a group of "finding" objects). Also propose reviewing naming syntax for collections throughout the schema to align the naming.

**Comment by brianrufgsa** [comment]
@adamb-kpmg while the name can't be identical, it certainly doesn't have to be an underscore. In fact, I believe I intended a dash and the underscore is a typo. It's an easy fix, which I'll make when I address a few related items in the very near future.

I'll have to defer to @david-waltermire-nist and/or @wendellpiez as to the explanation of why the name can't be identical. I know it's a JSON-only issue and doesn't apply to XML. 
Normally we just convert a singular to a plural, but that doesn't work with "results", which is why "group" is appended.

Count on it being changed to "results-group"

**Comment by wendellpiez** [comment]
In this particular case I wonder if we could have `result` as the singular name and `results` the grouping name. This is really a semantic question about the data, not a consequence of our working rule to keep singular and plural names distinct. (@brianrufgsa ?)

**Comment by brianrufgsa** [comment]
@wendellpiez I suppose we could if we accepted that a single "result" could have many observations and/or risks.

**Comment by wendellpiez** [comment]
Indeed - after hitting "Comment" yesterday I think I remembered this was at issue. I also think "results" and "result" look very similar, whereas the ideal or perfect grouping name looks enough like the singular name for the relation to be clear, but not so similar that it is confusing. E.g. "properties" as grouping name for "prop". Of the options we have considered so far, I think "results-group" passes this test the best.

**Comment by adamb-kpmg** [comment]
Sorry if I missed the logic…but are we doing this across the board, so a plural will be the singular + “group”? So objectives turns into objectives-group, assets becomes asset-group, test-methods becomes test-methods-group, etc?

My 2 cents is objectives, assets, etc. looks better, and this should be results.

Adam

**Comment by brianrufgsa** [comment]
@adamb-kpmg we are only discussing this change relative to results/results_group, and the standard has been simply the singular/plural (objective/objectives, asset/assets, etc.) 

I'm sold. The change will be result/results instead of results/results_group unless someone raises a good reason to do otherwise before I get to the change.

I have a few other syntax tweaks to make and intend to batch them together, as soon as I get a few other work items addressed.

**Comment by wendellpiez** [comment]
@brianrufgsa I think we can explain in docs that "result" can include multiple findings (`observation|risk` or as the case may be). This is also evident from their cardinality, but we can spell it out that this is a wrapper for the outcome of an assessment.

As you have also pointed out, there may be house rules governing whether and how risks (and observations) can be grouped. Calling the grouping a single "result" (which enables consolidating all the features common to a group of risks, say) may actually help with that.
