### ISSUE TITLE
Identify JSON-specific modeling differences

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#73]
Goals:

1. Identify specific differences between existing XML model and JSON model
2. Mechanisms for satisfying those differences per the colloquialisms of JSON

Dependencies:

1. XML->JSON conversions per Sprint 5

Acceptance Criteria:

1. Differences identified
2. Steps to address those differences are developed

**Comment by wendellpiez** [comment]
@anweiss @david-waltermire-nist please help prioritize questions regarding the production of sweet, pretty and idiomatic vs "dumb" JSON from the conversion scripts. I have a couple of ideas on approaches (as you may also) but they require development. Also, since this Issue was written, some work on the metaschema may have helped. (For example, Booleans now look more like what you expect.)

If you judge the problem to be not too acute given the current alignment, we could perhaps move the Issue to M2.

**Comment by anweiss** [comment]
@wendellpiez per some of our previous discussions, could you reiterate here how the metaschema can be used to flatten the JSON without data loss? More specifically, hoisting some of the data itself into the keys is a nice benefit of the JSON formatted OSCAL.

**Comment by david-waltermire-nist** [comment]
@wendellpiez I am good with pushing this to M2.

**Comment by david-waltermire-nist** [comment]
@anweiss I think this issue is addressed by #388 and #239. Let me know if I can mark this as a duplicate.

**Comment by anweiss** [comment]
@david-waltermire-nist yep, closing this in favor of #239.
