### ISSUE TITLE
Profile Resolver: Add ability to identify appropriate catalog or profile rlink entry

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/OSCAL#746]
# User Story:

As an OSCAL profile author, I want the ability to use a URI fragment in the import statement, then have the back-matter resource include multiple rlink fields linking all formats of the imported file.

The profile resolution utility should recognize when more than one rlink field is provided and determine the correct link to use, such as by using some combination of the media-type field and rel field.

## Goals:

Be able to specify both the XML and JSON versions of a catalog in the back-matter resource assembly, and have the XML-based profile resolver reliably use the XML link.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by SilentEsper** [comment]
I just ran into this type of issue. 
I have been simply storing the "NIST_SP-800-53_rev5_HIGH-baseline_profile" internally  as the "key" instead of the UUID
On Import I am chopping off the relative stuff the ".../.. or Https://" and the "XML or JSON" stuff at the end.
This lets me match on the filename of the profile.
It might be nice for Import Profile to support UUID matching or have more strict conditions in terms of what the schema allows.

**Comment by wendellpiez** [comment]
This is an important feature, but it raises questions I am not sure I am ready to answer in the prototype. Be that as it may, it must also be specified and written up as to particulars. `@media-type` on the `rlink` could perhaps be used to indicate the type of resource at the other end of the `rlink`. Hard questions include whether the published profile resolver prototype continues to support only XML, and (even if not) how it should support such dynamic resource type matching in operation.

**Comment by wendellpiez** [comment]
Currently working on an implementation that will read XML only (since this is an XSLT stack) from a (linked) `resource/rlink`, taking the first `rlink` available with either 'xml' in its `@media-type` or an `@href` ending with 'xml'. This is intended to cover almost every (XML) use case. We still have to develop guidelines regarding whether profile processors should approach this in general.

**Comment by wendellpiez** [comment]
A small set of unit tests for this feature has been added (it appears to work).
