### ISSUE TITLE
Add optional remarks to Property.

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#842]
# User Story:

As an OSCAL tool developer, I would like to be able to compose remarks about Properties.

## Goals:

One can imagine a Property as essential data element and an Annotation as a non-essential but useful meta-data element. Both would benefit from the ability to make remarks about the entity. Only Annotation allows for remarks presently.

Example: a Property x may have be assigned the value y, and the remarks may be that conditions a+b+c were contributing factors to this particular assignment. 

## Dependencies:

None.

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
This concept related to the "consolidate prop and annotation" idea, but seeks to maintain a semantic distinction between properties (of controls or in other contexts), and annotations. However, it may be difficult in practice either to define, or to enforce, a meaningful distinction there. (In the current model their semantics are effectively equivalent apart from `annotation` being annotatable, notwithstanding the implications of their names.) See #850.

**Comment by degenaro** [comment]
Definitions from Websters:

property - a quality or trait belonging and especially peculiar to an individual or thing
annotation - a note added by way of comment or explanation

Clearly two different meanings. In OSCAL each has a value and name and each could benefit by allowing remarks.

**Comment by wendellpiez** [comment]
:+1. The name 'annotation' is a bit of a kludge, and somewhat misleading (if not simply ambiguous). We are working on refactoring this.

**Comment by david-waltermire-nist** [comment]
This relates to #850, which @wendellpiez is referencing above.

When annotation was added to OSCAL, it was added to allow a model to have a "property" like object that could have a remark. We didn't add remark to properties, because we wanted to have a model construct that didn't allow a remark. This is turning out to be less ideal as the boundary between what is a property and what is an annotation is fairly murky. As a result we are going to propose that property and annotation be merged into a new property that allows for an optional value and remark. (#850)
