### ISSUE TITLE
Consider combining prop and annotation

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#850]
# User Story:

As an OSCAL content creator or tool, it is difficult to determine when prop or annotation is appropriate. They have similar models. It would be simpler if these concepts were combined into a single prop object.

## Goals:

1. Discuss with the community a proposal to combine prop and annotation, gaining consensus on the way forward.
2. Make the necessary metaschema changes.
3. Develop a content upconverter and update content in the OSCAL content and FedRAMP Automation repositories.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by brian-ruf** [comment]
Regardless of whether these are combined or not, I think it is also worth considering in this conversation whether to separate the extension functionality from the prop or annotation, to eliminate `@ns` confusion.

In other words, I think the cleanest approach is:
- eliminate `annotation`
- expand `prop` to include an `@value` flag and `remarks` child (effectively giving it the same ability as `annotation`).
- eliminate the optional `@ns` flag.
- add an `extension` field with a **required** `@ns` flag, and otherwise has the same construct as above (`@name`, `@value`, and optional child `remarks`)

I have long been concerned that many XPath and XSLT authors are writing queries for core OSCAL without including the `[not(@ns) or @ns="http:csrc.nist.gov/ns/oscal']`

**Comment by ohsh6o** [comment]
> I have long been concerned that many XPath and XSLT authors are writing queries for core OSCAL without including the [not(@ns) or @ns="http:csrc.nist.gov/ns/oscal']

Not that I have a definitive opinion yet of which approach might be preferrable to me, but I have received a Ruf cut by way of observation: Brian is correct, I am one such XSLT author who had to learn this the hard way and why I asked so many clarifying questions in the March 5th OSCAL Model Review meeting about proposed extension work.
