### ISSUE TITLE
Tutorial: Extension Mechanisms

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#857]
# User Story:

As an OSCAL content creator or consumer, I need guidance on how to use the various OSCAL extension points (i.e., property and links) to provide extended data.

This relates to a question posed in #542.

## Goals:

- Create a tutorial illustrating the use of the OSCAL extension mechanisms.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
Also consider `part` in this tutorial.

**Comment by ohsh6o** [comment]
As a community member, I would love to contribute in whatever way you deem helpful on this effort.

**Comment by ohsh6o** [comment]
I have provided my ongoing work on an example component with an extension for security tool parameters in [the OSCAL discussion forum](https://github.com/usnistgov/OSCAL/discussions/900) and would love feedback and know how I can work with those assigned to further this effort, if this extension work will help.

**Comment by Rene2mt** [comment]
This work is in progress.  For a preview of what will be covered in the tutorial, please see my [draft outline here](https://hackmd.io/@UE-2CUI2SlGqZQtexK6f3A/rJwxJHRsd).  I welcome any feedback.

**Comment by ohsh6o** [comment]
Provided some initial feedback as an outside peer, hope that helps and is not too forward.

I looked at this because there is some overlap with [FedRAMP Guidance in Section 3.1 in this document on page 28, along with other parts of this document and others here](https://raw.githubusercontent.com/GSA/fedramp-automation/44502e264c2673effa689fc3a708c9fe6249c514/documents/Guide_to_OSCAL-based_FedRAMP_Content.pdf). These are slightly out of date, and the draft versions are in [a shared drive we use with NIST (you have access)](https://drive.google.com/drive/folders/1yVy02A-bylMvQZMWpxiNDV48emh6tfxP).

This is great and would like to align our resources with this once this is official. Thanks for publishing your outline!

**Comment by aj-stein-nist** [comment]
Interesting follow-up requests for clarity on best practices with using OSCAL `@ns` for namespacing and extending OSCAL data here, relevant to perhaps touching up AC and working this issue to completion in 1.1.0?

https://gitter.im/usnistgov-OSCAL/Lobby?at=6273c50314df4e44f20e9e86

/cc @1z10 @mruge
