### ISSUE TITLE
Improve identifer usage and references in FedRamp profiles

### ISSUE THREAD

**Issue by david-waltermire** [usnistgov/OSCAL#89]
OSCAL uses identifiers and identifier references to link a profile entry to a control or control enhancement, to link an implementation entry to a profile entry and the underlying catalog, and to provide for relationships between controls and control enhancements. It is important for these identifiers to agree to keep referential integrity within the OSCAL instances.  Much of this inconsistency has been produced because the original profiles have been created manually. To fix these issues, a subject matter expert (SME) will need to review the content and make the necessary corrections. We need to identify an appropriate SME to complete this task.

**Comment by wendellpiez** [comment]
This issue concerns the integrity and correctness of the FedRAMP examples. Since this Issue was written, work by @brainrufgsa has probably addressed it, at least implicitly. (If so please feel free to mark the Issue as 'closable').

Cf also Issue #38, about tooling for cross-checking profiles against their catalogs.

**Comment by brianrufgsa** [comment]
PR #362 offers updated FedRAMP Profiles to address this issue. Recommend closing.

**Comment by iMichaela** [comment]
## 5/23/2019
Needs review and then close it (@brianrufgsa noted this issue is addressed in PR #362)
